x-app: &app
  build: .
  volumes:
    - .:/jumpa:cached
    - ./log/erlang-history:/log/erlang-history
    - ./log/shell-history:/log/shell-history
  environment:
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/jumpa_dev
    ERL_AFLAGS: -kernel shell_history enabled -kernel shell_history_path '"/log/erlang-history"'
    HISTSIZE: 10000
    HISTFILE: /log/shell_history

services:
  jumpa.shell:
    <<: *app
    command: sleep 1000000000000000000
    working_dir: /jumpa
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/jumpa_test
  jumpa.api:
    <<: *app
    command: /bin/sh -c "mix setup && elixir --name jumpa@jumpa.api --cookie jumpa -S mix phx.server --no-halt"
    working_dir: /jumpa/jumpa-api
    ports:
      - 4000:4000
  jumpa.world:
    <<: *app
    command: /bin/sh -c "mix setup && elixir --name jumpa@jumpa.world --cookie jumpa -S mix run --no-halt"
    working_dir: /jumpa/jumpa-world
  frontend:
    image: node:19-alpine3.16
    command: /bin/sh -c "npm i && npm run start"
    working_dir: /jumpa/jumpa-client/web/
    volumes:
      - .:/jumpa:cached
    ports:
      - 3000:3000
  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: "pg_isready -U postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./data/config.yml:/etc/kafkaui/dynamic_config.yaml
  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
volumes:
  postgres:
  kafka_data:
    driver: local
