x-app: &app
  build: .
  volumes:
    - .:/app:cached
    - ./log/erlang-history:/log/erlang-history
    - ./log/shell-history:/log/shell-history
  environment:
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/jumpa_dev
    ERL_AFLAGS: -kernel shell_history enabled -kernel shell_history_path '"/log/erlang-history"'
    HISTSIZE: 10000
    HISTFILE: /log/shell_history

services:
  shell:
    <<: *app
    command: sleep 1000000000000000000
    working_dir: /jumpa
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/jumpa_test

  api:
    <<: *app
    command: /bin/sh -c "mix setup && elixir --sname api --cookie gen_game -S mix phx.server --no-halt"
    working_dir: /app/api
    ports:
      - 4000:4000

  app:
    <<: *app
    command: /bin/sh -c "mix setup && elixir --sname app --cookie gen_game -S mix run --no-halt"
    working_dir: /app/app
    depends_on:
      kafka:
        condition: service_healthy

  world:
    <<: *app
    command: /bin/sh -c "mix setup && elixir --sname world --cookie gen_game -S mix run --no-halt"
    working_dir: /app/world
    environment:
      ENABLE_GAME_CONSUMER: true
    depends_on:
      kafka:
        condition: service_healthy

  frontend:
    image: node:19-alpine3.16
    command: /bin/sh -c "npm i && npm run start"
    working_dir: /app/client/web
    volumes:
      - .:/app:cached
    ports:
      - 3000:3000

  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: "pg_isready -U postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:9092 --list
      interval: 1s
      timeout: 15s
      retries: 3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092


volumes:
  postgres:
