services:
  gen_game:
    container_name: gen_game
    image: f4th4n/gen_game:latest
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/gen_game_prod
    depends_on:
      - postgres
    ports:
      - 4000:4000

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    healthcheck:
      test: "pg_isready -U postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gen_game_prod
    ports:
      - 5433:5432

volumes:
  postgres:
