x-app: &app
  build: .
  volumes:
    - .:/jumpa:cached
    - ./log/erlang-history:/log/erlang-history
    - ./log/shell-history:/log/shell-history
  environment:
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/jumpa_dev
    ERL_AFLAGS: -kernel shell_history enabled -kernel shell_history_path '"/log/erlang-history"'
    HISTSIZE: 10000
    HISTFILE: /log/shell_history

services:
  jumpa.shell:
    <<: *app
    command: sleep 1000000000000000000
    working_dir: /jumpa
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/jumpa_test
  jumpa.api:
    <<: *app
    command: /bin/sh -c "mix setup && elixir --name jumpa@jumpa.api --cookie jumpa -S mix phx.server --no-halt"
    working_dir: /jumpa/jumpa-api
    ports:
      - 4000:4000
  jumpa.world:
    <<: *app
    command: /bin/sh -c "mix setup && elixir --name jumpa@jumpa.world --cookie jumpa -S mix run --no-halt"
    working_dir: /jumpa/jumpa-world
  frontend:
    image: node:19-alpine3.16
    command: /bin/sh -c "npm i && npm run start"
    working_dir: /jumpa/jumpa-client/web/
    volumes:
      - .:/jumpa:cached
    ports:
      - 3000:3000
  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: "pg_isready -U postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

volumes:
  postgres:
