include:
  - ../../docker-compose.yml

services:
  quick_arcade:
    build: .
    container_name: quick_arcade
    command: /bin/sh -c "mix deps.get && elixir --sname quick_arcade --cookie g3ng4m3 -S mix run --no-halt"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - gen_game
  gen_game:
    environment:
      PLUGIN_MODE: erlang_rpc
